steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/<YOUR_GCP_PROJECT>/fsi-rm-mcp', '-f', 'mcp_servers/Dockerfile', '.']
images:
  - 'gcr.io/<YOUR_GCP_PROJECT>/fsi-rm-mcp'
